spring:
  mvc:
    hiddenmethod:
      filter:
        enabled=true
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    prefix : classpath:/templates/
    suffix : .html

file.dir: /Users/hwangdaeseon/Project/toy/src/main/resources/static/files/